sudo: false

language: node_js

node_js:
  - "8"
  - "10"

os:
  - osx
  - linux

cache: yarn

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn
  - yarn vscode:prepublish

script:
  - yarn --silent

notifications:
  email: false
